package DCourt.Screens.Quest;

/* loaded from: DCourt.jar:DCourt/Screens/Quest/Quests.class */
public interface Quests {
  public static final String townGuard =
      "{itMonster|Guard|50|50|50|20|20|40|{=|pic|Other/Guard.jpg}|{~|values|{=|passion|hostile}}|{~|pack|{@|Healing Salve|5}|{@|Marks|500}}|{~|temp|{#|Actions|2}|{#|fight|4}}|{~|gear|{%|Steel Sword|20}|{%|Half Plate|20}|bless}|{~|opts|bribe|backstab|swindle|control}|{itText|text|The palace is guarded by a $stout$ $name$ who refuses you passage.  \"Only nobles and merchants with castle permits are allowed to pass me by.\"  He waggles his fingers in the universal signal for \'bribe me\'.|{~|$name$|Soldier|Pikeman|Knight|Trooper}|{~|$stout$|stout|sturdy|tough|brawny|strong}}}";
  public static final String castleGuard =
      "{itMonster|Guard|100|100|100|40|40|80|{=|pic|Other/Guard.jpg}|{~|values|{=|passion|hostile}}|{~|pack|{@|Gold Apple|5}|{@|Marks|1000}}|{~|temp|{#|Actions|3}|{#|fight|8}}|{~|gear|{%|Bill Hook|20}|{%|Full Plate|20}}|{~|opts|bribe|backstab|swindle|control}|{itText|text|The palace is guarded by a $stout$ $name$ who refuse you passage.  \"Only nobility may pass these borders\", he declaims.  You see his hand surreptitiously making the universal signal for \'bribe me\'.|{~|$name$|Soldier|Pikeman|Knight|Trooper}|{~|$stout$|stout|sturdy|tough|brawny|strong}}}";
  public static final String vortexGuard =
      "{itMonster|Evil Fred|150|150|150|60|60|120|{=|pic|Fields/Soldier.jpg}|{~|values|{=|passion|aggressive}}|{~|pack|{@|Gold Apple|5}|{@|Marks|500}}|{~|temp|{#|Actions|2}|{#|fight|2}|{%|magic|50}}|{~|gear|{%|Bill Hook|20}|{%|Full Plate|20}}|{~|opts|riddle|backstab|control}|{itText|text|Evil Fred stands guarding the vortex.  \"Only those who prove themselves worthy may enter this place.\"  Evil Fred chuckles evilly, while giving you the evil eye.  \"You need only answer my riddle. You like games, don\'t you?\"}}";
  public static final String faeryRing =
      "{itMonster|Faery|1|16|9|0|0|500|{=|pic|Other/Faery.jpg}|{~|values|{=|passion|timid}|adjust}|{~|pack|{@|Panic Dust|3}|{@|Blinding Dust|3}}|{~|temp|{#|Actions|3}|{#|magic|2}}|{~|gear|{%|Faery Fists|0}|{%|Sparkly Wings|0}}|{~|opts|capture|swindle|control}|{itText|text|You are making your way towards smoke in the distance when a $SOUND$ sound catches your attention.  Pushing your way past some $BUSH$, you find a small $POND$ with a $SPARK$ Faery floating above it.|{~|$SOUND$|tinkling|giggling|splashing|whistling|raspberry|chuckling|rustling}|{~|$BUSH$|bushes|shrubs|branches|boulders|old fences}|{~|$POND$|pond|brook|creek|puddle}|{~|$SPARK$|sparkling|giggling|glowing|glistening|playful}}}";
  public static final String fieldRodent =
      "{itMonster|Rodent|4|8|6|1|0|0|{=|pic|Fields/Rodent.jpg}|{~|values|{=|passion|aggressive}}|{~|pack|{@|Teeth|8}}|{~|gear|{%|Yellow Teeth|0}|{%|Mangy Fur|0}|disease}|{~|opts|feed|backstab|control}|{itText|text|Searching through the fields you come upon a $adj$ $name$ rooting $mood$ through a $junk$. The $name$ spies you and spins around, snarling viciously.|{~|$name$|Rat|Gerbil|Rabbit|Ferret|Vole|Mole|Squirrel}|{~|$adj$|evil|deadly|giant|black|smelly|cruel}|{~|$mood$|listlessly|savagely|quietly|messily|noisily}|{~|$junk$|backpack|haybale|trash heap|corpse|bush|shrub|puddle}}}";
  public static final String fieldGoblin =
      "{itMonster|Goblin|6|6|6|3|2|-3|{=|pic|Fields/Goblin.jpg}|{~|values|{=|passion|hostile}}|{~|pack|{@|Food|1}|{@|Marks|12}}|{~|gear|{%|Rusty Dagger|40}|{%|Rotting Leathers|0}}|{~|opts|bribe|backstab|swindle|control}|{itText|text|You are wandering past a $junk$ when suddenly a $adj$ $name$ leaps out and accosts you. It grunts out a message in some $odd$ language, but you think the $name$ wants money.|{~|$name$|Goblin|Brownie|Sprite|Dwarf|Pixie}|{~|$adj$|frightened|jittery|jumpy|angry|shaky}|{~|$junk$|bush|tree|rock|barrow|mound}|{~|$odd$|odd|wierd|strange|foreign}}}";
  public static final String fieldGypsy =
      "{itMonster|Gypsy|9|8|15|6|2|2|{=|pic|Fields/Gypsy.jpg}|{~|values|{=|passion|hostile}}|{~|pack|{@|Marks|8}|{@|Torch|1}|{@|Rope|1}|{%|Silver Throwing Knife|1}}|{~|gear|{%|Throwing Knife|50}|{%|Leather Jacket|25}}|{~|opts|trade|backstab|swindle|control}|{itText|text|You stroll over a small $junk$ in the landscape and discover the camp of a $adj$ $name$.  He grins wickedly, then rapidly corners you.  The $name$ plays with his knife while suggesting that you \'trade\'.|{~|$name$|Gypsy|Beggar|Vagabond|Traveller}|{~|$adj$|sly|sneaky|suspicious|arrogant|dusty}|{~|$junk$|rise|mound|hillock}}}";
  public static final String fieldCentaur =
      "{itMonster|Centaur|12|8|12|10|6|2|{=|pic|Fields/Centaur.jpg}|{~|values|{=|passion|defensive}}|{~|pack|{@|Marks|25}|{%|Quartz|50}|{%|Quartz|50}}|{~|gear|{%|Long Bow|15}|{%|Horse Barding|0}}|{~|opts|trade|swindle|control}|{itText|text|While striding towards a distant stand of trees, you mount a rise to discover $aadj$ $name$ watching you $adv$.  It\'s bow is not pointed at you, but that could change in an instant.|{~|$name$|Centaur|Half Horse|Horse Man|Man Horse|Centaur Runt|Centaur Bard|Centaur Sage|Centaur Hero}|{~|$aadj$|a noble| proud| sturdy|a healthy|a wary|a young|an aged|an arrogant}|{~|$adv$|quietly|sadly|calmly|cautiously|warily}}}";
  public static final String fieldMerchant =
      "{itMonster|Merchant|3|8|5|2|1|1|{=|pic|Fields/Oldman.jpg}|{~|values|{=|passion|passive}}|{~|pack|{@|Marks|25}|{@|Marks|25}|{@|Torch|1}|{@|Rope|1}|{@|Food|1}}|{~|gear|{%|Staff|20}|{%|Clothes|20}}|{~|opts|help|backstab|swindle|control}|{itText|text|You come upon $aadj$ $man1$ sitting beside a broken $item$.  He looks tired and distraught.  The $man2$ asks if you could kindly help to fix his $item$.|{~|$aadj$|a sad|a quiet|an unhappy|an old|an ugly}|{~|$man1$|man|guy|fellow|gent|bloke}|{~|$man2$|man|guy|fellow|gent|bloke}|{~|$item$|wagon|water pump|wind mill|backpack}|{~|$name$|Merchant|Trader|Cobbler|Miller}}}";
  public static final String fieldWizard =
      "{itMonster|Wizard|1|3|2|6|12|10|{=|pic|Fields/Oldman.jpg}|{~|values|{=|passion|defensive}|adjust}|{~|pack|{@|Marks|10}|{@|Marks|10}|{%|Opal|60}|{%|Healing Salve|20}|{%|Bottled Faery|1}}|{~|temp|{#|magic|1}}|{~|gear|{%|Staff|20}|{%|Clothes|0}}|{~|opts|help|backstab|swindle|control}|{itText|text|You come upon $aadj$ $man1$ sitting beside a broken $item$.  He looks tired and distraught.  The $man2$ asks if you could kindly help to fix his $item$.|{~|$aadj$|a sad|a quiet|an unhappy|an old|an ugly}|{~|$man1$|man|guy|fellow|gent|bloke}|{~|$man2$|man|guy|fellow|gent|bloke}|{~|$item$|wagon|water pump|wind mill|backpack}|{~|$name$|Wizard|Sorceror|Druid|Mage}}}";
  public static final String fieldSoldier =
      "{itMonster|Soldier|13|13|13|8|8|8|{=|pic|Fields/Soldier.jpg}|{~|values|{=|passion|hostile}|adjust}|{~|pack|{@|Marks|30}|{@|Marks|30}|{%|Healing Salve|50}|{%|Silver Pike|1}}|{~|gear|{%|Pike|25}|{%|Half Plate|25}}|{~|opts|bribe|backstab|swindle|control}|{itText|text|You are following a road towards the village of $town$ when you encounter a $mood$ $name$ blocking the road. He $loud$ announces that you are required to pay a \'toll\' if you wish to pass.|{~|$name$|Mercenary|Swordsman|Soldier|Crusader|Knight|Sell Sword}|{~|$mood$|rough|angry|brutal|greedy|lazy|vulgar}|{~|$town$|Hampton|Forstead|Alwin|Shindale|Selwin|Brook}|{~|$loud$|vigorously|loudly|rudely|savagely|crudely}}}";
  public static final String forestBoar =
      "{itMonster|Boar|16|12|12|8|8|10|{=|pic|Forest/Boar.jpg}|{~|values|{=|passion|aggressive}}|{~|pack|{%|Tusk|80}|{%|Tusk|80}|{@|Food|5}|{@|Food|5}|{%|War Tusk|20}}|{~|gear|{%|Pointy Tusks|0}|{%|Furry Hide|0}}|{~|opts|feed|backstab|control}|{itText|text|A $adj$ $name$ comes barreling out of the under brush and immediately charges you, squealing with $mood$. You dodge the first rush, then spin about and taunt it by crying, \"$tag$\"|{~|$name$|Boar|Pig|Porker|Swine|Shoat|Sow|Tusker|Razorback}|{~|$adj$|black|ugly|sour|foul|huge|giant|hairy}|{~|$mood$|rage|fury|anger|confusion|enthusiasm|hunger}|{~|$tag$|Ole!|Come and get it piggy!|Oink Oink ya Doink!|Yummy, pork for supper!|Eat blade pig breath!|Care to dance?}}}";
  public static final String forestOrc =
      "{itMonster|Orc|20|12|18|10|10|0|{=|pic|Forest/Orc.jpg}|{~|values|{=|passion|aggressive}}|{~|pack|{@|Marks|30}|{@|Marks|30}|{@|Food|6}|{%|Healing Salve|30}|{@|Opal|1}}|{~|gear|{%|Battle Axe|20}|{%|Mithril Mail|20}}|{~|opts|bribe|backstab|swindle|control}|{itText|text|You take a turn in the forest path, round a $obj$ and come face to face with a $name$.  It seems $mood$ to meet you.  The $name$ waves its axe between you then stares at your purse longingly.|{~|$name$|War Orc|High Kobold|Troll Runt|Orc Skald|Orc Thrall}|{~|$obj$|tree|hedge|mound|boulder|ledge|trunk}|{~|$mood$|amused|pleased|happy|glad|delighted}}}";
  public static final String forestElf =
      "{itMonster|Elf|25|18|30|15|10|12|{=|pic|Forest/Elf.jpg}|{~|values|{=|passion|defensive}}|{~|pack|{@|Marks|20}|{@|Marks|20}|{@|Garnet|1}|{%|Healing Salve|50}|{%|Silver Elf Bow|1}}|{~|gear|{%|Elf Bow|20}|{%|Mithril Mail|20}}|{~|opts|trade|backstab|swindle|control}|{itText|text|You are following the tracks of a $beast$ when a sudden whistle catches your attention.  In the branches overhead sits $amood$ $name$ with a drawn bow.  You may have just trespassed on $area$.|{~|$name$|Elf|Sidhe|Drow|Sylph|Faery}|{~|$beast$|giant boar|unicorn|gryphon|wild stag|cougar|snot|bear|lion}|{~|$area$|elven land|a burial site|holy ground|sacred turf|the Faery Realm}|{~|$amood$|an angry|a wary|a cautious|an arrogant|a High}}}";
  public static final String forestGryphon =
      "{itMonster|Gryphon|30|30|15|15|18|12|{=|pic|Forest/Gryphon.jpg}|{~|values|{=|passion|hostile}}|{~|pack|{@|Opal|1}|{@|Garnet|1}|{@|Emerald|1}|{@|Ruby|1}|{%|Mandrake Root|20}|{%|Identify Scroll|50}|{%|Mercury Sandals|20}}|{~|gear|{%|Sharp Beak|0}|{%|Sturdy Feathers|0}|{%|Bottled Faery|2}}|{~|opts|riddle|swindle|control}|{itText|text|You are exploring a $adj$ $place$ when a huge figure swoops down upon you.  It is $aproud$ $name$ staring at you with supreme arrogance.  \"Answer my riddle $worm$, and I shall let you pass.\"|{~|$name$|Gryphon|Gryphlet|Gryphette|Gryphon Bard|Gryphon Hero}|{~|$aproud$|a haughty|a proud|a vain|an arrogant|an imperious|a lofty|an aloof|a lordly|a smug}|{~|$adj$|small|hidden|twisted|dirty}|{~|$place$|valley|ridge|stream|lake|pit|vale}|{~|$worm$|worm|human|mortal|morsel|slug|snail}}}";
  public static final String forestSnot =
      "{itMonster|Snot|60|30|12|8|8|-10|{=|pic|Forest/Snot.jpg}|{~|values|{=|passion|hostile}}|{~|pack|{@|Marks|150}|{@|Marks|150}|{%|Seltzer Water|80}|{%|Ruby|10}|{%|Elf Bow|10}|{%|Mithril Mail|10}|{%|Dwarf Axe|10}}|{~|gear|{%|Snot Lobber|0}|{%|Mucous Layer|0}|disease}|{~|opts|feed|backstab|control}|{itText|text|Its a Snot.  A big ugly pile of goo.  It slides relentlessly through the forest muttering, \" $feed$ ... $feed$ \" over and over.  It smells like $stink$.  From the looks of things, it considers you to be $food$.|{~|$stink$|dung|garbage|rotting meat|fish guts}|{~|$food$|food|lunch|dinner|supper|breakfast}|{~|$feed$|Feed Me|Hungry|Need Food|Must Eat}}}";
  public static final String forestUnicorn =
      "{itMonster|Unicorn|35|30|50|18|24|16|{=|pic|Forest/Unicorn.jpg}|{~|values|{=|passion|defensive}|adjust}|{~|pack|{#|Gold Apple|1}|{@|Gold Apple|3}|{@|Emerald|2}|{@|Emerald|2}|{%|Enchant Scroll|20}}|{~|temp|{%|magic|33}}|{~|gear|{%|Unicorn Horn|20}|{%|Magic Aura|0}}|{~|opts|help|backstab|swindle}|{itText|text|You come upon an enchanted grove where a Unicorn is trying to dislodge apples from a golden tree.  It\'s lack of opposable thumbs is proving to be an insurmountable difficulty.}}";
  public static final String moundGate =
      "{itMonster|Gate|25|25|25|12|12|10|{=|pic|Mound/Gate.jpg}|{~|values|{=|passion|hostile}}|{~|pack|{@|Marks|100}|{@|Gold Nugget|2}|{%|Cross Bow|20}}|{~|gear|{%|Cross Bows|0}|{%|Thick Doors|0}}|{~|opts|bribe|swindle|control}|{itText|text|The strange mound has a hole leading into the earth. Guarding the hole is a wooden $door$ defended by $mood$ little Goblin $name$ who shout  \"Haltzez or we\'ll shootz!\" as they fire on you.|{~|$name$|Guards|Soldiers|Troopers|Troops}|{~|$door$|door|gate|palisade|wall}|{~|$mood$|itchy|greedy|smelly|excited}}}";
  public static final String moundGang =
      "{itMonster|Gang|40|25|25|5|10|10|{=|pic|Mound/Gang.jpg}|{~|values|{=|passion|hostile}}|{~|pack|{@|Marks|100}|{@|Gold Nugget|3}|{%|Goblin Pick|20}|{%|Miners Cap|20}}|{~|gear|{%|Picks+Shovels|0}|{%|Miner Caps|0}}|{~|opts|help|swindle|control}|{itText|text|You come accross a $name$ of Goblins trying to $dig$ open a collapsed passage.  From their $mood$ cries, you come to believe that the $debris$ may conceal some of their comrades.|{~|$name$|Gang|Crowd|Group|Band|Party|Pack}|{~|$dig$|pry|lever|tunnel|dig|shovel}|{~|$debris$|debris|wreckage|rubble|rocks|dirt}|{~|$mood$|desperate|fearful|grim|bleak|dismal|forlorn}}}";
  public static final String moundRager =
      "{itMonster|Berzerker|30|20|20|15|15|25|{=|pic|Mound/Rager.jpg}|{~|values|{=|passion|aggressive}}|{~|pack|{@|Teeth|8}|{@|Teeth|8}|{@|Gold Nugget|3}|{%|Map to Treasury|15}|{%|Silver Weird Knife|1}}|{~|temp|{#|fight|3}}|{~|gear|{%|Weird Knife|15}|{%|Goblin Shield|15}|disease}|{~|opts|feed|backstab|control}|{itText|text|A $mood$ Goblin $name$ charges you from the darkness. It is foul, noisy, drooling, frothing and smelly.In fact, this wild creature epitomizes everything that goblins admire.|{~|$name$|Berzerker|Fanatic|Suicide|Lunatic|Maniac|Zealot}|{~|$mood$|screaming|shrieking|foaming|rabid|frenzied}}}";
  public static final String moundThief =
      "{itMonster|Thief|25|25|25|10|16|30|{=|pic|Mound/Thief.jpg}|{~|values|{=|passion|hostile}}|{~|pack|{@|Marks|100}|{@|Gold Nugget|2}|{%|Turnip|50}|{%|Thief Insurance|25}}|{~|temp|{#|thief|1}}|{~|gear|{%|Weird Knife|20}|{%|War Boots|20}}|{~|opts|trade|backstab|swindle|control}|{itText|text|A $sly$ goblin motions you into a side tunnel. He holds up a \'magic\' turnip he thinks you will buy. The $slimy$ little $name$ grins ferociously as you examine the pale root.|{~|$name$|Thug|Bravo|Thief|Hoodlum|Crook|Swindler|Cutpurse}|{~|$sly$|sly|sneaky|shifty|furtive|stealthy}|{~|$slimy$|slimy|sleazy|shabby|slippery|tricky}}}";
  public static final String moundWorm =
      "{itMonster|Worm|60|20|20|12|12|10|{=|pic|Mound/Worm.jpg}|{~|values|{=|passion|hostile}}|{~|pack|{%|Seltzer Water|80}|{@|Gold Nugget|3}|{%|Goblin Pike|10}|{%|Miners Cap|10}|{%|War Boots|10}}|{~|temp|{#|worm|5}}|{~|gear|{%|Sucking Mouth|0}|{%|Segmented Rings|0}|disease}|{~|opts|feed|control}|{itText|text|$abig$ $name$ comes humping and wriggling down the tunnel!  The passage is filled from wall to wall, you have no escape from the $name$ as it plunges towards you trying to $eat your torch.|{~|$name$|Worm|Earthworm|Wyrm|Slug|Serpent}|{~|$abig$|A huge|An enormous|A gigantic|A monolithic|A tremendous}|{~|$eat$|eat|gobble|swallow|engulf}}}";
  public static final String moundMage =
      "{itMonster|Mage|25|30|25|12|20|15|{=|pic|Mound/Mage.jpg}|{~|values|{=|passion|hostile}}|{~|pack|{@|Marks|80}|{@|Marks|80}|{@|Quartz|3}|{@|Opal|2}|{@|Garnet|1}|{%|Glow Scroll|30}|{%|Identify Scroll|50}|{%|Silver Staff|1}|{%|Bottled Faery|3}}|{~|temp|{#|magic|2}|{%|thief|50}}|{~|gear|{%|Magic Staff|20}|{%|Magic Robes|20}}|{~|opts|bribe|backstab|swindle|control}|{itText|text|You encounter a well dressed goblin who speaks your language.  \"Well human,\" it says, \"please to tell me why I shouldn\'t be killink you?\"  You get the feeling it isn\'t joking.|{~|$name$|Mage|Wizard|Sorcerer|Warlock|Summoner}}}";
  public static final String moundGuard =
      "{itMonster|Guard|40|25|25|18|18|15|{=|pic|Mound/Guard.jpg}|{~|values|{=|passion|aggressive}}|{~|pack|{@|Marks|150}|{@|Marks|150}|{@|Gold Nugget|3}|{@|Gold Nugget|3}|{@|Healing Salve|2}|{%|Identify Scroll|80}}|{~|temp|{%|thief|30}|{%|fight|30}}|{~|gear|{%|Goblin Pike|20}|{%|Goblin Mithril|20}}|{~|opts|bribe|backstab|swindle|control}|{itText|text|A patrolling Goblin Guard catches you in the Treasury.  \"$cry$\" , it shrieks, \"you not be herez!\"  It points its $shake$ pike at you, but you can tell that it is $look$ at your purse.|{~|$cry$|Haltzez!|Ztop!|Hey Youz!|Waitzez!|Aiie!}|{~|$shake$|quivering|shaking|wavering|quaking}|{~|$look$|staring|looking|eyeing|examining|watching}}}";
  public static final String moundVault =
      "{itMonster|Vault|50|50|50|18|24|10|{=|pic|Mound/Vault.jpg}|{~|values|{=|passion|defensive}}|{~|pack|{@|Marks|500}|{@|Marks|500}|{@|Gold Nugget|4}|{@|Gold Nugget|4}|{@|Ruby|2}|{@|Emerald|3}|{@|Garnet|4}|{%|Map to Throne Room|15}|{%|Bless Scroll|10}|{%|Luck Scroll|10}|{%|Glow Scroll|15}|{%|Enchant Scroll|10}}|{~|temp|{%|fight|70}}|{~|gear|{%|XBows & Pikes|0}|{%|Iron Grate|0}}|{~|opts|bribe|swindle|control}|{itText|text|Down a side passage you spy an Iron Gate. It is $held$ by $mood$ Goblin $name$ who shout obscenities at you.  Behind the gate you see piles of gold and gems. You have found a goblin treasure vault.|{~|$name$|Soldiers|Guards|Troopers|Warriors|Fighters|Halbediers}|{~|$held$|being held|defended|protected|manned}|{~|$mood$|frenzied|excited|frenetic|energetic}}}";
  public static final String moundChamp =
      "{itMonster|Champion|50|40|40|20|26|30|{=|pic|Mound/Champ.jpg}|{~|values|{=|passion|aggressive}}|{~|pack|{@|Marks|300}|{@|Marks|300}|{@|Gold Nugget|3}|{@|Gold Nugget|3}|{@|Seltzer Water|2}|{%|Enchant Scroll|10}|{%|Bless Scroll|10}|{%|Luck Scroll|10}}|{~|temp|{#|thief|1}|{#|fight|2}}|{~|gear|{%|Flaming Sword|20}|{%|Goblin Plate|20}}|{~|opts|backstab|control}|{itText|text|While investiging what looks like a $church$ you encounter a $strong$ Goblin $name$ wielding a flaming blade.  It stands about hip high to you, but charges nonetheless with little regard for its own safety.|{~|$name$|Champion|Hero|Knight|Paladin}|{~|$church$|church|temple|cathedral|chapel|shrine}|{~|$strong$|mighty|powerful|tough|brawny|stalwart|formidable}}}";
  public static final String moundQueen =
      "{itMonster|Queen|40|50|50|20|20|40|{=|pic|Mound/Queen.jpg}|{~|values|{=|passion|aggressive}|adjust}|{~|pack|{@|Gold Nugget|5}|{@|Gold Nugget|5}|{@|Gold Apple|3}|{@|Panic Dust|3}|{%|Map to Vortex|15}}|{~|temp|{#|magic|2}|{#|thief|1}}|{~|gear|{%|Terror Rod|20}|{%|Crystal Crown|30}|panic}|{~|opts|seduce|backstab|control}|{itText|text|Sneaking through a marbled $hall$ you come upon a $room$ where a Goblin Queen resides surrounded by $kissup$ fawning on her.  Queen $name$ spots you first, and motions you forward into her lair...|{~|$name$|Idara|Eudora|Yarrish|Anzig|Oreole|Ugtig}|{~|$hall$|corridor|hallway|passage|gallery|vestibule|portico}|{~|$room$|large hall|vestibule|dining hall|chamber|meeting hall|grand sanctum}|{~|$kissup$|lackeys|sycophants|toadies|courtiers|flunkies|minions}}}";
  public static final String hillsGoat =
      "{itMonster|Giant Goat|40|35|35|10|10|16|{=|pic|Hills/Goat.jpg}|{~|values|{=|passion|aggressive}}|{~|pack|{%|Horn|80}|{%|Horn|80}|{@|Food|10}|{@|Food|10}|{@|Quartz|2}|{@|Garnet|2}|{%|Ginseng Root|30}}|{~|temp|{#|goat|3}}|{~|gear|{%|Rams Horn|20}|{%|Mangy Fur|0}}|{~|opts|feed|backstab|control}|{itText|text|While rappeling down from a ledge, you encounter a Giant Goat.  It immediately attacks, trying to knock you off the $ledge$ into the stony crags below.|{~|$ledge$|ledge|mountain|cliff|ridge}}}";
  public static final String hillsBasilisk =
      "{itMonster|Basilisk|40|35|35|10|10|16|{=|pic|Hills/Basilisk.jpg}|{~|values|{=|passion|aggressive}}|{~|pack|{@|Quartz|4}|{@|Opal|3}|{@|Garnet|2}|{@|Emerald|1}|{@|Blinding Dust|2}|{@|Blinding Dust|2}}|{~|gear|{%|Evil Gaze|0}|{%|Scaly Skin|0}|blind}|{~|opts|feed|backstab|control}|{itText|text|You pull yourself to the top of a steep cliff, only to confront $amad$ Basilisk.  Its colorful crest rises as it hisses at you.  Then the $beast$ charges and tries to snap a bite out of your precious hide.|{~|$amad$|an angry|a mad|a peeved|an irate|a furious|a livid}|{~|$beast$|beast|creature|brute|lizard|reptile|viper}}}";
  public static final String hillsWyvern =
      "{itMonster|Wyvern|40|35|35|15|25|20|{=|pic|Hills/Wyvern.jpg}|{~|values|{=|passion|aggressive}}|{~|pack|{@|Opal|2}|{@|Garnet|2}|{@|Emerald|2}|{@|Ruby|2}|{#|Gold Apple|1}|{@|Gold Apple|2}|{%|Panic Dust|80}|{%|Panic Dust|80}}|{~|temp|{%|magic|50}}|{~|gear|{%|Raking Claws|0}|{%|Great Feathers|0}|panic}|{~|opts|swindle|control}|{itText|text|You are climbing a talus slope when a slide of rocks nearly crushes you.  Looking up, you spy a malevolent Wyvern pushing rocks off a ledge above.}}";
  public static final String hillsTroll =
      "{itMonster|Troll|50|50|30|20|20|20|{=|pic|Hills/Troll.jpg}|{~|values|{=|passion|aggressive}}|{~|pack|{@|Marks|300}|{@|Marks|300}|{%|Silver Weird Knife|1}||{@|Ruby|2}|{@|Ruby|2}|{@|Rope|10}|{@|Rope|10}|{%|Panic Dust|20}|{%|Blinding Dust|20}|{%|Mandrake Root|20}|{@|Troll Wart|6}}|{~|temp|{@|thief|2}|{@|fight|2}}|{~|gear|{%|Huge Claws|0}|{%|Knotted Muscles|0}|disease}|{~|opts|help|swindle|control}|{itText|text|You see a $ugly$ Troll trying to $fix$ his $broken$ bridge.  It is tying boards together with a small supply of rope.  The Troll is not making much progress.|{~|$fix$|fix|repair|mend|patch|rebuild}|{~|$broken$|broken|damaged|ruined|ravaged}|{~|$ugly$|warty|speckled|scarred|spotted|scabby}}}";
  public static final String hillsSphinx =
      "{itMonster|Sphinx|60|30|40|24|24|20|{=|pic|Hills/Sphinx.jpg}|{~|values|{=|passion|aggressive}}|{~|pack|{@|Ruby|3}|{@|Ruby|3}|{%|Identify Scroll|80}|{%|Enchant Scroll|20}|{%|Flame Scroll|20}|{%|Luck Scroll|20}|{%|Bless Scroll|20}|{%|Thief Insurance|50}|{%|Map to Vortex|10}|{@|Gold Apple|2}|{@|Gold Apple|2}|{%|Bottled Faery|4}}|{~|temp|{@|fight|2}}|{~|gear|{%|Razor Claws|0}|{%|Magic Feathers|0}}|{~|opts|riddle|swindle}|{itText|text|You are examining a giant nest littered with scrolls, when a Sphinx swoops down to face you. \"How dare you intrude!\" it screams, \"I give you one chance to live... answer my riddle!\"}}";
  public static final String hillsGiant =
      "{itMonster|Giant|80|40|40|20|20|0|{=|pic|Hills/Giant.jpg}|{~|values|{=|passion|hostile}|adjust}|{~|pack|{@|Marks|800}|{@|Marks|800}|{%|Silver Giant Maul|1}||{%|Rutter for Hie Brasil|10}|{%|Youth Elixir|5}|{@|Healing Salve|8}|{@|Seltzer Water|4}|{@|Ginseng Root|2}}|{~|gear|{%|Giant Maul|20}|{%|Shaggy Mane|0}}|{~|opts|bribe|backstab|swindle|control}|{itText|text|You climb a tree for a better look, then you realize that trees don\'t normally have hair on them. You look up and up as the Giant looks down and down.}}";
  public static final String hillsDragon =
      "{itMonster|Dragon|250|250|250|100|100|200|{=|pic|Hills/Dragon.jpg}|{~|values|{=|passion|aggressive}|adjust}|{~|pack|{@|Gold Apple|8}|{@|Gold Apple|8}|{@|Ginseng Root|5}|{@|Seltzer Water|8}|{@|Blinding Dust|8}|{@|Panic Dust|8}|{@|Marks|10000}|{@|Marks|10000}|{@|Dragon Scales|10}}|{~|temp|{#|Actions|5}|{@|fight|8}|{#|magic|2}}|{~|gear|{%|Fire Breath|0}|{%|Magic Scales|0}}|{~|opts|bribe|backstab}|{itText|text|The entrance to the cave is guarded by $abig$ $name$ Dragon.  It looks to be asleep, except that $reason$.  As you approach, a deep rumbling shakes the ground.  It\'s $laugh$!|{~|$name$|Red|Green|Blue|Purple|Blue|Orange|Muave}|{~|$abig$|a huge|an enormous|a tremendous|an immense}|{~|$laugh$|laughing|chuckling|chortling}|{~|$reason$|it has one eye open|it\'s tail is sweeping|it\'s ears are turned towards you|it grins suddenly|it\'s nose is slowly leaking smoke}}}";
}
